4-reviews
reawilliams20/nc-games pull request #1
Opened 2023-01-09 15:37 UTC by reawilliams20

2023-01-09 16:10 UTC, lewispricey requested changes
Great work so far on this Andrea. Realy like the semantic HTML and they way you've setup your base url to keep the code clean.

I've added a few adjustments as comments:
* Would be great to setup isLoading at this stage to show a user on a slow connection that something is happening
* For the Reviews page I wouldn't recommend showing the full Body or like buttons so a user could easly scroll though to find the review they're looking for, these would be better place on the individual review pages but this is a design desision so completely up to you.

Overall great work!

Please raise another PR once you have loading setup.

2023-01-09 16:10 UTC, lewispricey commented on src/ReviewList.jsx
> +    console.log(listOfReviews)
Please don't forget to remove any console.logs before PR :)

2023-01-09 16:10 UTC, lewispricey commented on src/ReviewCard.jsx
> +            <button>👍</button>
For the review card we wouldn't want to display the body (or atleast the whole body) or the like buttons, this would be shown and done on the individual review page when a user clicks into a review.

2023-01-09 16:10 UTC, lewispricey commented on src/apis.js
> +const gamesApi = axios.create({baseURL: 'https://andrea-nc-games.onrender.com/api/'})
Really like the use of the axios.create to set a base url, this makes changing hosts if you ever need to super easy! 👍

2023-01-09 16:10 UTC, lewispricey commented on src/ReviewList.jsx
> +    <section>
Nice use of semantic HTML tags.

2023-01-09 16:10 UTC, lewispricey commented on src/ReviewList.jsx
> +    useEffect(() => {
Would be great to setup your isLoading at this point to make clear to a user on a slower connection the app is loading.

2023-01-09 16:10 UTC, lewispricey commented on src/ReviewCard.jsx
> +        <img src={img_url} alt={`Image of review ${review_id}`} width="100" height="100" />
Like the use of the variable review_id in the alt tag.

2023-01-10 09:50 UTC, RichardNeat approved these changes
Nice one Andrea - just a couple of comments below. Try and keep it so that all code submitted on each branch is only relevant to the current ticket, try not to move on to future implementation too much. Have a look at the routing relating to categories and comments that you have begun to work on but only worry about finishing them off when it is needed.

2023-01-10 09:50 UTC, RichardNeat commented on src/Nav.jsx
> +                <Link to={`/reviews?category=strategy`}><li> Strategy </li></Link>
Hi just some advice for when you get to implementing these routes in a later ticket. We don't need to hard code each category option, if we do we will run into issues later if a new category ever gets added, plus it's very DRY code. We have parametric endpoints to help us in this situation - drop me a message if you'd like a recap on that :)

2023-01-10 09:50 UTC, RichardNeat commented on src/Nav.jsx
> +                <Link to={`/${username}/comments`}><li>My Comments</li></Link>
When we get to looking at comments you will see that the comments are attached to a review rather than a user

2023-01-10 10:11 UTC, merged