8-post-comment
reawilliams20/nc-games pull request #5
Opened 2023-01-11 10:42 UTC by reawilliams20

2023-01-11 11:02 UTC, reawilliams20 commented
backend requires username to post comment. frontend requires author to display optimistic rendering of a new comments username. in PostComment.jsx

2023-01-11 11:28 UTC, leekli requested changes
Hi Andrea, well done on this ticket so far.

I've posted comments throughout.

I have 2 main change requests which I would like to see implemented:

1. As a user, you are making me input a username, but I have no idea what username to use. This is making an assumption that I know what I'm meant to type. I actually don't.... infact to make sure I had the right username I had to go to your backend api and check the users endpoint to see what I'm allowed to use. I would advise getting rid of this completely, and just post a comment as a hard coded user for now. We will look at 'React Context' tomorrow which will help with the whole logging in/which user thing. However for now, don't make me physically write in a username... it's not usual to be expected to do this on a comment section on a site/app.
2. I can actually post an empty comment, which I shouldn't be able to do. It then shows up in the api as an empty string "" - please look at fixing this.

Please review the 2 main points above, along with other comment feedback in the PR, implement all the changes, and submit a new pull request once complete.

2023-01-11 11:28 UTC, leekli commented on src/CommentList.jsx
> +            <PostComment setListOfComments={setListOfComments}/>
Love that you've split this out into a separate component, well done

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +    console.log(users)
This can be removed

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +        })
OK this is interesting - getting all the users first.

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +            <p>Comment Added!</p>
Nice use of a success message

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +                <textarea name="comment" id="comment"></textarea><br></br>
So I can actually submit an empty comment...

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +                <textarea name="comment" id="comment"></textarea><br></br>
textarea is a good element to use here, well done!

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +        <div className="postComment">
Is there a more appropiate semantic element we could use instead of a div? [https://www.w3schools.com/html/html5_semantic_elements.asp](url)

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +        created_at: "Just now..."
Yeah I like this line!

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +        })
Well done for optimistic rendering here

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +        username: e.target[0].value,
I'd put this as a hard coded user for now

2023-01-11 11:28 UTC, leekli commented on src/PostComment.jsx
> +        })
If you do the comment posting as a hard coded user, then this useeffect may not be needed here any longer.

React Context, covered tomorrow, will help with this functionality later on :)

2023-01-11 11:55 UTC, leekli requested changes
Hi Andrea, thanks for making these changes. Good to see I can no longer submit a comment which is empty also - well done!

I can see that you've sorted the hard coded user but I still can't post a comment as I'm still been made to put a username into a text box ? Does this input field on line 53 in PostComment.jsx serve a purpose anymore?

Also on a side note - the styling on mobile view doesn't look right... the image of the review is hanging over the border, and the comments are scrunched together. I'll send you a video on Slack so you can see what I see.

Well done so far Andrea, but just a few more changes required above to get this over the line.

Please implement (and fix the styling/mobile responsive view design) and then submit a new request once complete.

2023-01-11 11:55 UTC, leekli commented on src/PostComment.jsx
>                  <input type="text" name="username" id="username" required></input><br></br>
What purpose is this serving still being here?

2023-01-12 08:48 UTC, leekli approved these changes
Much better, thanks Andrea.

You are free to merge this branch.

2023-01-12 08:51 UTC, merged